baseURL = 'https://connar.github.io/'
languageCode = 'en-us'
title = 'Journal of Connar'
theme = 'PaperMod'

[outputs]
  home = ["HTML", "RSS", "JSON"] # necessary for search

[params.fuseOpts]
  isCaseSensitive = true
  shouldSort = true
  location = 0
  distance = 1000
  threshold = 0.4
  minMatchCharLength = 0
  keys = ["title", "permalink", "summary", "content"]

[params]
  ShowBreadCrumbs = true
  ShowReadingTime = true
  ShowPostNavLinks = true
  ShowCodeCopyButtons = true
  hideSummary = true

[params.cover]
  linkFullImages = true



[params.profileMode]
  enabled = true
  title = "Connar's Blog"
  subtitle = "Sisiphus eventually became Zarathustra"
  imageUrl = "/img/sisiphus.png"
  imageTitle = "connar"
  imageWidth = 240
  imageHeight = 240

[[params.profileMode.buttons]]
  name = "Malware"
  url = "/malware"

[[params.profileMode.buttons]]
  name = "Posts"
  url = "/posts"

[[params.profileMode.buttons]]
  name = "My Challenges"
  url = "/mychallenges"

[[params.profileMode.buttons]]
  name = "Projects"
  url = "/projects"

[[params.socialIcons]]
  name = "github"
  url = "https://github.com/connar"

[[menu.main]]
  identifier = "categories"
  name = "Categories"
  url = "/categories/"
  weight = 10
[[menu.main]]
  identifier = "tags"
  name = "Tags"
  url = "/tags/"
  weight = 20
[[menu.main]]
  identifier = "archives"
  name = "Archives"
  url = "/archives/"
  weight = 30
[[menu.main]]
  identifier = "mychallenges"
  name = "My Challenges"
  url = "/mychallenges/"
  weight = 40
[[menu.main]]
  identifier = "posts"
  name = "Posts"
  url = "/posts/"
  weight = 50
[[menu.main]]
  identifier = "projects"
  name = "Projects"
  url = "/projects/"
  weight = 60
[[menu.main]]
  identifier = "about"
  name = "About"
  url = "/about/"
  weight = 70
[[menu.main]]
  identifier = "search"
  name = "Search"
  url = "/search/"
  weight = 80


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true